{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "bc64f5fd",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\u001b[34m\u001b[1mwandb\u001b[0m: Currently logged in as: \u001b[33mosmane\u001b[0m (use `wandb login --relogin` to force relogin)\n"
     ]
    },
    {
     "data": {
      "text/html": [
       "\n",
       "                    Syncing run <strong><a href=\"https://wandb.ai/osmane/projet-s6-pieces/runs/1swfx3a7\" target=\"_blank\">olive-spaceship-3</a></strong> to <a href=\"https://wandb.ai/osmane/projet-s6-pieces\" target=\"_blank\">Weights & Biases</a> (<a href=\"https://docs.wandb.com/integrations/jupyter.html\" target=\"_blank\">docs</a>).<br/>\n",
       "\n",
       "                "
      ],
      "text/plain": [
       "<IPython.core.display.HTML object>"
      ]
     },
     "metadata": {},
     "output_type": "display_data"
    },
    {
     "data": {
      "text/html": [
       "<button onClick=\"this.nextSibling.style.display='block';this.style.display='none';\">Display W&B run</button><iframe src=\"https://wandb.ai/osmane/projet-s6-pieces/runs/1swfx3a7?jupyter=true\" style=\"border:none;width:100%;height:420px;display:none;\"></iframe>"
      ],
      "text/plain": [
       "<wandb.sdk.wandb_run.Run at 0x255a43d9df0>"
      ]
     },
     "execution_count": 1,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import wandb\n",
    "import tensorflow as tf\n",
    "\n",
    "wandb.init(project=\"projet-s6-pieces\", entity=\"osmane\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "6d807efc",
   "metadata": {},
   "outputs": [],
   "source": [
    "from keras.datasets import mnist\n",
    "\n",
    "(train_images, train_labels), (test_images, test_labels) = mnist.load_data()\n",
    "\n",
    "train_images = train_images.reshape((60000, 28 * 28))\n",
    "train_images = train_images.astype('float32') / 255\n",
    "\n",
    "test_images = test_images.reshape((10000, 28 * 28))\n",
    "test_images = test_images.astype('float32') / 255\n",
    "\n",
    "from tensorflow.keras.utils import to_categorical\n",
    "\n",
    "train_labels = to_categorical(train_labels)\n",
    "test_labels = to_categorical(test_labels)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 12,
   "id": "64570012",
   "metadata": {},
   "outputs": [],
   "source": [
    "wandb.config = {\n",
    "  \"learning_rate\": 0.001,\n",
    "  \"epochs\": 100,\n",
    "  \"batch_size\": 128\n",
    "}\n",
    "\n",
    "from keras import models\n",
    "from keras import layers\n",
    "\n",
    "network = models.Sequential()\n",
    "network.add(layers.Dense(512, activation='relu', input_shape=(28 * 28,)))\n",
    "network.add(layers.Dense(10, activation='softmax'))\n",
    "\n",
    "network.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['accuracy'])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "dd0d4bf7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/5\n"
     ]
    },
    {
     "ename": "InternalError",
     "evalue": " Attempting to perform BLAS operation using StreamExecutor without BLAS support\n\t [[node sequential_3/dense_6/MatMul\n (defined at F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\util\\tf_stack.py:193)\n]] [Op:__inference_train_function_862]\n\nErrors may have originated from an input operation.\nInput Source operations connected to node sequential_3/dense_6/MatMul:\nIn[0] IteratorGetNext:\t\nIn[1] sequential_3/dense_6/MatMul/ReadVariableOp:\n\nOperation defined at: (most recent call last)\n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\runpy.py\", line 194, in _run_module_as_main\n>>>     return _run_code(code, main_globals, None,\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\runpy.py\", line 87, in _run_code\n>>>     exec(code, run_globals)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n>>>     app.launch_new_instance()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n>>>     app.start()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 677, in start\n>>>     self.io_loop.start()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n>>>     self.asyncio_loop.run_forever()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\asyncio\\base_events.py\", line 570, in run_forever\n>>>     self._run_once()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\asyncio\\base_events.py\", line 1859, in _run_once\n>>>     handle._run()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\asyncio\\events.py\", line 81, in _run\n>>>     self._context.run(self._callback, *self._args)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 461, in dispatch_queue\n>>>     await self.process_one()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 450, in process_one\n>>>     await dispatch(*args)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 357, in dispatch_shell\n>>>     await result\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 652, in execute_request\n>>>     reply_content = await reply_content\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in do_execute\n>>>     res = shell.run_cell(code, store_history=store_history, silent=silent)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 532, in run_cell\n>>>     return super().run_cell(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2768, in run_cell\n>>>     result = self._run_cell(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2814, in _run_cell\n>>>     return runner(coro)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n>>>     coro.send(None)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3012, in run_cell_async\n>>>     has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3191, in run_ast_nodes\n>>>     if await self.run_code(code, result, async_=asy):\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3251, in run_code\n>>>     exec(code_obj, self.user_global_ns, self.user_ns)\n>>> \n>>>   File \"C:\\Users\\eosma\\AppData\\Local\\Temp\\ipykernel_22616\\2341454374.py\", line 2, in <module>\n>>>     network.fit(train_images, train_labels, epochs=5, batch_size=128, callbacks=[WandbCallback()])\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\wandb\\integration\\keras\\keras.py\", line 168, in new_v2\n>>>     return old_v2(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\training.py\", line 1216, in fit\n>>>     tmp_logs = self.train_function(iterator)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 150, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 910, in __call__\n>>>     result = self._call(*args, **kwds)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 975, in _call\n>>>     return self._stateless_fn(*args, **kwds)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3129, in __call__\n>>>     filtered_flat_args) = self._maybe_define_function(args, kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3557, in _maybe_define_function\n>>>     graph_function = self._create_graph_function(args, kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3392, in _create_graph_function\n>>>     func_graph_module.func_graph_from_py_func(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1143, in func_graph_from_py_func\n>>>     func_outputs = python_func(*func_args, **func_kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 672, in wrapped_fn\n>>>     out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1118, in autograph_handler\n>>>     return autograph.converted_call(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\training.py\", line 878, in train_function\n>>>     return step_function(self, iterator)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\training.py\", line 867, in step_function\n>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 1316, in run\n>>>     return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 2892, in call_for_each_replica\n>>>     return self._call_for_each_replica(fn, args, kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 3695, in _call_for_each_replica\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\training.py\", line 860, in run_step\n>>>     outputs = model.train_step(data)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\training.py\", line 808, in train_step\n>>>     y_pred = self(x, training=True)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1083, in __call__\n>>>     outputs = call_fn(inputs, *args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\sequential.py\", line 373, in call\n>>>     return super(Sequential, self).call(inputs, training=training, mask=mask)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\functional.py\", line 451, in call\n>>>     return self._run_internal_graph(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\functional.py\", line 589, in _run_internal_graph\n>>>     outputs = node.layer(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1083, in __call__\n>>>     outputs = call_fn(inputs, *args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\layers\\core\\dense.py\", line 199, in call\n>>>     outputs = tf.matmul(a=inputs, b=self.kernel)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 150, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py\", line 1096, in op_dispatch_handler\n>>>     return dispatch_target(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py\", line 3700, in matmul\n>>>     return gen_math_ops.mat_mul(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\ops\\gen_math_ops.py\", line 6033, in mat_mul\n>>>     _, _, _op, _outputs = _op_def_library._apply_op_helper(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 744, in _apply_op_helper\n>>>     op = g._create_op_internal(op_type_name, inputs, dtypes=None,\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 689, in _create_op_internal\n>>>     return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3697, in _create_op_internal\n>>>     ret = Operation(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2101, in __init__\n>>>     self._traceback = tf_stack.extract_stack_for_node(self._c_op)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\util\\tf_stack.py\", line 193, in extract_stack_for_node\n>>>     return _tf_stack.extract_stack_for_node(\n>>> ",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[1;31mInternalError\u001b[0m                             Traceback (most recent call last)",
      "Input \u001b[1;32mIn [16]\u001b[0m, in \u001b[0;36m<module>\u001b[1;34m\u001b[0m\n\u001b[0;32m      1\u001b[0m \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;21;01mwandb\u001b[39;00m\u001b[38;5;21;01m.\u001b[39;00m\u001b[38;5;21;01mkeras\u001b[39;00m \u001b[38;5;28;01mimport\u001b[39;00m WandbCallback\n\u001b[1;32m----> 2\u001b[0m \u001b[43mnetwork\u001b[49m\u001b[38;5;241;43m.\u001b[39;49m\u001b[43mfit\u001b[49m\u001b[43m(\u001b[49m\u001b[43mtrain_images\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mtrain_labels\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mepochs\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m5\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mbatch_size\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[38;5;241;43m128\u001b[39;49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[43mcallbacks\u001b[49m\u001b[38;5;241;43m=\u001b[39;49m\u001b[43m[\u001b[49m\u001b[43mWandbCallback\u001b[49m\u001b[43m(\u001b[49m\u001b[43m)\u001b[49m\u001b[43m]\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mF:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\wandb\\integration\\keras\\keras.py:168\u001b[0m, in \u001b[0;36mpatch_tf_keras.<locals>.new_v2\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m    166\u001b[0m     \u001b[38;5;28;01mfor\u001b[39;00m cbk \u001b[38;5;129;01min\u001b[39;00m cbks:\n\u001b[0;32m    167\u001b[0m         set_wandb_attrs(cbk, val_data)\n\u001b[1;32m--> 168\u001b[0m \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[43mold_v2\u001b[49m\u001b[43m(\u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43margs\u001b[49m\u001b[43m,\u001b[49m\u001b[43m \u001b[49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[38;5;241;43m*\u001b[39;49m\u001b[43mkwargs\u001b[49m\u001b[43m)\u001b[49m\n",
      "File \u001b[1;32mF:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\utils\\traceback_utils.py:67\u001b[0m, in \u001b[0;36mfilter_traceback.<locals>.error_handler\u001b[1;34m(*args, **kwargs)\u001b[0m\n\u001b[0;32m     65\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m \u001b[38;5;167;01mException\u001b[39;00m \u001b[38;5;28;01mas\u001b[39;00m e:  \u001b[38;5;66;03m# pylint: disable=broad-except\u001b[39;00m\n\u001b[0;32m     66\u001b[0m   filtered_tb \u001b[38;5;241m=\u001b[39m _process_traceback_frames(e\u001b[38;5;241m.\u001b[39m__traceback__)\n\u001b[1;32m---> 67\u001b[0m   \u001b[38;5;28;01mraise\u001b[39;00m e\u001b[38;5;241m.\u001b[39mwith_traceback(filtered_tb) \u001b[38;5;28;01mfrom\u001b[39;00m \u001b[38;5;28mNone\u001b[39m\n\u001b[0;32m     68\u001b[0m \u001b[38;5;28;01mfinally\u001b[39;00m:\n\u001b[0;32m     69\u001b[0m   \u001b[38;5;28;01mdel\u001b[39;00m filtered_tb\n",
      "File \u001b[1;32mF:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\eager\\execute.py:58\u001b[0m, in \u001b[0;36mquick_execute\u001b[1;34m(op_name, num_outputs, inputs, attrs, ctx, name)\u001b[0m\n\u001b[0;32m     56\u001b[0m \u001b[38;5;28;01mtry\u001b[39;00m:\n\u001b[0;32m     57\u001b[0m   ctx\u001b[38;5;241m.\u001b[39mensure_initialized()\n\u001b[1;32m---> 58\u001b[0m   tensors \u001b[38;5;241m=\u001b[39m pywrap_tfe\u001b[38;5;241m.\u001b[39mTFE_Py_Execute(ctx\u001b[38;5;241m.\u001b[39m_handle, device_name, op_name,\n\u001b[0;32m     59\u001b[0m                                       inputs, attrs, num_outputs)\n\u001b[0;32m     60\u001b[0m \u001b[38;5;28;01mexcept\u001b[39;00m core\u001b[38;5;241m.\u001b[39m_NotOkStatusException \u001b[38;5;28;01mas\u001b[39;00m e:\n\u001b[0;32m     61\u001b[0m   \u001b[38;5;28;01mif\u001b[39;00m name \u001b[38;5;129;01mis\u001b[39;00m \u001b[38;5;129;01mnot\u001b[39;00m \u001b[38;5;28;01mNone\u001b[39;00m:\n",
      "\u001b[1;31mInternalError\u001b[0m:  Attempting to perform BLAS operation using StreamExecutor without BLAS support\n\t [[node sequential_3/dense_6/MatMul\n (defined at F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\util\\tf_stack.py:193)\n]] [Op:__inference_train_function_862]\n\nErrors may have originated from an input operation.\nInput Source operations connected to node sequential_3/dense_6/MatMul:\nIn[0] IteratorGetNext:\t\nIn[1] sequential_3/dense_6/MatMul/ReadVariableOp:\n\nOperation defined at: (most recent call last)\n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\runpy.py\", line 194, in _run_module_as_main\n>>>     return _run_code(code, main_globals, None,\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\runpy.py\", line 87, in _run_code\n>>>     exec(code, run_globals)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel_launcher.py\", line 16, in <module>\n>>>     app.launch_new_instance()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\traitlets\\config\\application.py\", line 846, in launch_instance\n>>>     app.start()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\kernelapp.py\", line 677, in start\n>>>     self.io_loop.start()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tornado\\platform\\asyncio.py\", line 199, in start\n>>>     self.asyncio_loop.run_forever()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\asyncio\\base_events.py\", line 570, in run_forever\n>>>     self._run_once()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\asyncio\\base_events.py\", line 1859, in _run_once\n>>>     handle._run()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\asyncio\\events.py\", line 81, in _run\n>>>     self._context.run(self._callback, *self._args)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 461, in dispatch_queue\n>>>     await self.process_one()\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 450, in process_one\n>>>     await dispatch(*args)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 357, in dispatch_shell\n>>>     await result\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\kernelbase.py\", line 652, in execute_request\n>>>     reply_content = await reply_content\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\ipkernel.py\", line 359, in do_execute\n>>>     res = shell.run_cell(code, store_history=store_history, silent=silent)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\ipykernel\\zmqshell.py\", line 532, in run_cell\n>>>     return super().run_cell(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2768, in run_cell\n>>>     result = self._run_cell(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 2814, in _run_cell\n>>>     return runner(coro)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\IPython\\core\\async_helpers.py\", line 129, in _pseudo_sync_runner\n>>>     coro.send(None)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3012, in run_cell_async\n>>>     has_raised = await self.run_ast_nodes(code_ast.body, cell_name,\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3191, in run_ast_nodes\n>>>     if await self.run_code(code, result, async_=asy):\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\IPython\\core\\interactiveshell.py\", line 3251, in run_code\n>>>     exec(code_obj, self.user_global_ns, self.user_ns)\n>>> \n>>>   File \"C:\\Users\\eosma\\AppData\\Local\\Temp\\ipykernel_22616\\2341454374.py\", line 2, in <module>\n>>>     network.fit(train_images, train_labels, epochs=5, batch_size=128, callbacks=[WandbCallback()])\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\wandb\\integration\\keras\\keras.py\", line 168, in new_v2\n>>>     return old_v2(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\training.py\", line 1216, in fit\n>>>     tmp_logs = self.train_function(iterator)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 150, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 910, in __call__\n>>>     result = self._call(*args, **kwds)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 975, in _call\n>>>     return self._stateless_fn(*args, **kwds)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3129, in __call__\n>>>     filtered_flat_args) = self._maybe_define_function(args, kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3557, in _maybe_define_function\n>>>     graph_function = self._create_graph_function(args, kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\eager\\function.py\", line 3392, in _create_graph_function\n>>>     func_graph_module.func_graph_from_py_func(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1143, in func_graph_from_py_func\n>>>     func_outputs = python_func(*func_args, **func_kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\eager\\def_function.py\", line 672, in wrapped_fn\n>>>     out = weak_wrapped_fn().__wrapped__(*args, **kwds)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 1118, in autograph_handler\n>>>     return autograph.converted_call(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\training.py\", line 878, in train_function\n>>>     return step_function(self, iterator)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\training.py\", line 867, in step_function\n>>>     outputs = model.distribute_strategy.run(run_step, args=(data,))\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 1316, in run\n>>>     return self._extended.call_for_each_replica(fn, args=args, kwargs=kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 2892, in call_for_each_replica\n>>>     return self._call_for_each_replica(fn, args, kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\distribute\\distribute_lib.py\", line 3695, in _call_for_each_replica\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\training.py\", line 860, in run_step\n>>>     outputs = model.train_step(data)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\training.py\", line 808, in train_step\n>>>     y_pred = self(x, training=True)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1083, in __call__\n>>>     outputs = call_fn(inputs, *args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\sequential.py\", line 373, in call\n>>>     return super(Sequential, self).call(inputs, training=training, mask=mask)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\functional.py\", line 451, in call\n>>>     return self._run_internal_graph(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\functional.py\", line 589, in _run_internal_graph\n>>>     outputs = node.layer(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 64, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\engine\\base_layer.py\", line 1083, in __call__\n>>>     outputs = call_fn(inputs, *args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\utils\\traceback_utils.py\", line 92, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\keras\\layers\\core\\dense.py\", line 199, in call\n>>>     outputs = tf.matmul(a=inputs, b=self.kernel)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\util\\traceback_utils.py\", line 150, in error_handler\n>>>     return fn(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\util\\dispatch.py\", line 1096, in op_dispatch_handler\n>>>     return dispatch_target(*args, **kwargs)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\ops\\math_ops.py\", line 3700, in matmul\n>>>     return gen_math_ops.mat_mul(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\ops\\gen_math_ops.py\", line 6033, in mat_mul\n>>>     _, _, _op, _outputs = _op_def_library._apply_op_helper(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\framework\\op_def_library.py\", line 744, in _apply_op_helper\n>>>     op = g._create_op_internal(op_type_name, inputs, dtypes=None,\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\framework\\func_graph.py\", line 689, in _create_op_internal\n>>>     return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 3697, in _create_op_internal\n>>>     ret = Operation(\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\framework\\ops.py\", line 2101, in __init__\n>>>     self._traceback = tf_stack.extract_stack_for_node(self._c_op)\n>>> \n>>>   File \"F:\\Machine_Learning\\Anaconda\\envs\\keras_ml\\lib\\site-packages\\tensorflow\\python\\util\\tf_stack.py\", line 193, in extract_stack_for_node\n>>>     return _tf_stack.extract_stack_for_node(\n>>> "
     ]
    }
   ],
   "source": [
    "from wandb.keras import WandbCallback\n",
    "network.fit(train_images, train_labels, epochs=5, batch_size=128, callbacks=[WandbCallback()])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "10ce7cba",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.8.12"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
